name: SignInCommand
main: com.github.hibi_10000.plugins.signincommand.SignInCommand
version: ${project.version}
author: Hibi_10000
api-version: 1.16
website: https://dev.bukkit.org/projects/sign-in-command
commands:
  signincommand:
    aliases: [sc, sic, signcommand]
    permission: signincommand.setup
    permission-message: Unknown command. Type "/help" for help.
permission:
  signincommand:
    default: op
    children:
      signincommand.setup: true
  signincommand.setup:
    default: op
    description: Use /signincommand command.
default-permission: op
