name: SignInCommand
main: com.github.hibi_10000.plugins.signincommand.SignInCommand
version: ${project.version}
author: Hibi_10000
api-version: 1.16
website: https://dev.bukkit.org/projects/sign-in-command
commands:
  sic:
    aliases: [sc, signincommand, signcommand]
    permission: signincommand.setup
    permission-message: Unknown command. Type "/help" for help.
parmission:
  signincommand:
    default: op
    children:
      signincommand.setup: true
  signincommand.setup:
    default: op
    description: /sic command.
default-parmission: op
