name: SignInCommand
main: jp.minecraft.hibi_10000.plugins.SignInCommand
version: 1.0.0
author: Hibi_10000
api-version: 1.16
description: |
  §aDistribution:§b https://dev.bukkit.org/projects/signincommand
  §bCopyright © 2021 Hibi_10000 All rights reserved.
commands:
  sic:
    aliases: [sc, signincommand, signcommand]
    permission: signincommand.setup
    permission-message: Unknown command. Type "/help" for help.
parmission:
  signincommand:
    default: op
    children:
      signincommand.setup: true
  signincommand.setup:
    default: op
    description: /sic command.
default-parmission: op
